name: cleaner.matrix,rocks  # Replace with your desired environment name
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - black>=24.10.0
      - mypdns>=1.0.5
      - requests>=2.26.0
